### ISSUE TITLE
Incorrect deps in PyPi

### ISSUE THREAD

**Issue by quasarj** [lunemec/eveapi2#1]
Github issues may not be the right place to log this, but currently your PyPi package is missing bs4 in its dependency list.

**Comment by lunemec** [comment]
@quasarj thank you for reporting this. I'll add it and reupload to pypi.

**Comment by lunemec** [comment]
Fixed in https://github.com/lunemec/eveapi2/commit/738fef73a1a95795869ada5a9394b608e9938292

I uploaded new version that is in shiny new wheel format! see: http://pythonwheels.com/

**Comment by lunemec** [comment]
I noticed lxml and py.test was also missing from dependencies. I added them as well.
